# This is the build environment to produce the mobotix binary(s)
FROM amd64/ubuntu:bionic-20200921

RUN apt-get update && apt-get install -y \
    gcc \
    make \
    g++

ADD mobotix_sdk /build
RUN cd /build/eventstreamclient/plugin-client && \
    ln -s toolchain_x86.cfg toolchain.cfg && \
    cd /build/eventstreamclient/lib/Linux && \
    ln -s libeventstreamclient_x86.a libeventstreamclient.a

RUN /usr/bin/make -C /build/eventstreamclient/plugin-client/thermal-raw
RUN cp /build/eventstreamclient/plugin-client/thermal-raw/build/thermal-raw /thermal-raw
