name: CI

on:
  pull_request:
    branches: [main, master]

env:
  TEST_TAG: user/mobotix:test

jobs:
  build_and_unit_test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Set up QEMU for multi-arch builds
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker buildx for multi-arch builds
        uses: docker/setup-buildx-action@v1

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and export to Docker
        uses: docker/build-push-action@v2
        with:
          context: .
          load: true
          tags: ${{ env.TEST_TAG }}

      - name: Run Unit Test
        run: |
          docker run --rm --entrypoint python3 ${{ env.TEST_TAG }} app/test.py
